final Map<String, String> ar = {
  "Create_New_Account":"انشاء حساب جديد",
  "Forgotten_account?":"هل نسيت كلمة السر؟",
  "Phone":"التليفون",
  "Password":"كلمة المرور",
  "Re_Password":"تأكيد كلمة السر",
  "Sign_in":"تسجيل الدخول",
  "m1":"قائمه طلبات المساعده الخاصه بى",
  "m2":"قائمه مقدمى الخدمه",
  "mafcode":"الابلاغ عن المفقودات",
  "wazayfi":"الوظايف والاعمال",
  "things":"things to be done",
  "helpmony":"المساعدات الماليه",
  "elwazelmafcode":"قائمه المفقودات",
  "waza":"عرض وظيفه",
  "profile":"الملف الشخصى",
  "posts":"البوستات",
  "Contact":"تواصل معنا",


  "about":"نبذه عن التطبيق",
  "m3":"قائمة طلبات المساعده الخاصه بى",
  "request":"اعلان طلب وظيفه",
  "things2":"things to be done list",
  "help":"قائمة طلبات المساعده",
  "m4":"قائمة مقدمى الخدمه",
  "mafcode2":"قائمة المفقودات",
  "offer":"قائمة اعلان وظائف",
  "things3":"خدمة التنقلات",
  "help2":"قائمةالمساعدات ",
  "log out":"تسجيل خروج",



  "Continue_with":"التسجيل ب",
  "Phone_number":"رقم الهاتف",
  "Email":"البريد الإلكترونى",
  "Continue":"متابعة",
  "Set_birthday":"تاريخ الميلاد",
  "ِAddress":"العنوان",
  "Home":"الرئيسه",
  "Send":"إرسال",
  "Exit":"إغلاق",
  "Register":"التسجيل",
  "Name":"الاسم",
  "Identification":"الهوية",
  "Theme_Options":"المظهر",
  "Share_My_code":"مشاركه الكود",
  "LOG_OUT":"تسجيل خروج",
  "Dark":"داكن",
  "Light":"فاتح",
  "upgrade":"تطوير الاشتراك",
  "language":"اللغه",

  "Accept":"موافق",
  "cancel":"رفض",

};