final Map<String, String> en = {
  "Create_New_Account": "Create New Account",
  "Forgotten_account?": "Forgotten account?",
  "Phone":"Phone number",
  "Password": "Password",
  "Sign_in": "Sign in",
  "m1":"My list of help requests",
  "m2":"List of service providers",
  "mafcode":"Report lost items",
  "wazayfi":"Jobs and business",
  "things":"things to be done",
  "helpmony":"financial aid",
  "elwazelmafcode":"Lost List",
  "waza":"Job offer",
  "profile":"Profile personly",
   "about":"About the app",
   "m3":"My list of help requests",
  "request":"Job application advertisement",
  "things2":"things to be done list",
  "m4":"list of service providers",
  "mafcode2":"Lost List",
  "offer":"List of job advertisements",
  "things3":"Transfer service",
  "log out":"log out",
  "help":"List of requests for assistance",
  "help2":"Help List",
  "posts":"posts",
  "Contact":"Contact Us",


  "Full_Name": "Full Name",

  "Re_Password": "Re Password",

  "Continue_with": "Continue with",
  "Phone_number": "Phone number",
  "Email": "Email",
  "Continue": "Continue",
  "Set_birthday": "Set birthday",
  "ِAddress": "ِAddress",
  "Section": "Section",
  "Male": "Male",
  "Female": "Female",
  "CONDITION_TEXT": "I agree with & condition",
  "Home": "Home",
  "Sections": "Sections",
  "Browse": "Browse",
  "Message": "Message",
  "Profile": "Profile",
  "Verification_code": "VERIFICATION CODE",
  "Resend": "Resend",
  "Subscription": "Subscription",
  "Annual": "Annual",
  "Semi-annual": "Semi-annual",
  "Monthly": "Monthly",
  "Privacy & Policy": "PRIVACY & POLICY",
  "MASTER_CARD": "MASTER CARD",
  "VISA": "VISA",
  "COMPANY": "COMPANY",
  "Enter_code_otp": "Enter codeOTP",
  "Send": "Send",
  "Exit": "Exit",
  "Register": "Registration",
  "Name": "Name",
  "Bio": "Bio",
  "Code": "Code",
  "Identification": "Identification",
  "Social media": "Social media",
  "WhatsApp": "WhatsApp",
  "Facebook": "Facebook",
  "Telegram": "Telegram",
  "Instagram": "Instagram",
  "Viber": "Viber",
  "Website": "Website",
  "ALL": "ALL",
  "Stores": "Stores",
  "Health": "Health",
  "Services": "Services",
  "Education": "Education",
  "DISCOUNT": "DISCOUNT",
  "Are_You": "Are You ?",
  "trader": "trader",
  "Factory": "Factory",
  "User": "User",
  "My_store": "My store",
  "Store_nearby": "Store nearby",
  "Best_rated": "Best rated",
  "About_us": "About us",
  "PRIVACY_POLICY": "PRIVACY POLICY",
  "Contact_us": "Contact_us",
  "Product": "Product",
  "productSearchText": "Search product,service,and more..",
  "storeSearchText": "Search stores...",
  "Filter": "Filter",
  "Sort": "Sort",
  "statistic": "Statistic",
  "Shipping_Address": "Shipping Address",
  "My_Order": "My Order",
  "Theme_Options": "Theme Options",
  "Share_My_code": "Share My code",
  "LOG_OUT": "LOG OUT",
  "Dark": "Dark",
  "Light": "Light",
  "upgrade": "Upgrade",
  "language": "Language",
  "view_all": "View All",
  "TotalOrder": "Total Order",
  "ToDayOrder": "ToDay Order",
  "NumberOfFollowers": "Number Of Followers",
  "NumberOfItems": "Number Of Items",
  "NumberOfPoints": "Number Of Points",
  "NumberOfCodeShare": "Number Of Code Share",
  "Items": "Items",
  "OrderID": "Order ID",
  "OrderDetails": "Order Details",
  "OrderDate": "Order Date",
  "ReceiverName": "Receiver Name",
  "NumberItems": "Number Items",
  "ReceiverMobile": "Receiver Mobile",
  "ShippingAddress": "Shipping Address",
  "TotalAmount": "Total Amount",
  "Accept": "Accept",
  "cancel": "Cancel",
  "Quantily": "Quantity",
  "Search_by": "Search by",
  "Stores nearby": "Stores nearby",
  "Price(low to high)": "Price(low to high)",
  "Price(high to low)": "Price(high to low)",
  "Star Rating(Highest first)": "Star Rating(Highest first)",
  "Star Rating(lowest first)": "Star Rating(lowest first)",
  "Rate": "Rate",
  "Price": "Price",
  "brand": "brand",
  "services": "services",
  "geographical": "geographical",
  "Add Product": "Add Product",
  "Description": "Description",
  "ProductName": "Product Name",
  "Number of Pieces": "Number of Pieces",
  "Category": "Category",
  "appearing for": "appearing for",
  "Followers": "Followers",
  "public": "public",
  "Add Image": "Add Image",
  "Add": "Add",
  "Location": "Location",
  "Edit Profile": "Edit Profile",
  "Follow": "Follow",
  "Chat": "Chat",
  "sub_sections":"SubSection",
  "sections":"Sections",
  "continue":"Continue",
  "send_order":"Send Order",
  "confirm_order":"Confirm Order",
  "number_items":"Number Items",
  "other_address":"Other Address",
  "add":"Add",
  "your_order":"Your Order",
  "success":"has been successfuly placed",
  "ok":"Ok",
  "city":"City",
  "country":"Country",
  "street":"Street",
  "postalCode":"Postal Code",




};
