
import 'package:chat_app/views/Changelost/Changelost.dart';
import 'package:chat_app/views/about/deliverAbout.dart';
import 'package:chat_app/views/about/helpAbout.dart';
import 'package:chat_app/views/about/jobAbout.dart';
import 'package:chat_app/views/about/mafcodAbout.dart';
import 'package:chat_app/views/login/newPassword.dart';
import 'package:chat_app/views/profile/Contact.dart';

abstract class Routes {
  static const INITIAL = '/';
  static const LOGIN = '/LOGIN';
  static const USER_FIRST_REGISTER = '/USER_FIRST_REGISTER';
  static const USER_SECOND_REGISTER = '/USER_SECOND_REGISTER';
  static const CONTROL = '/home_view';
  static const CONDITIONS = '/CONDITIONS';
  static const VERIFICATION_CODE = '/VERIFICATION_CODE';
  static const FIRST_SUBSCRIPTION = '/FIRST_SUBSCRIPTION';
  static const SECOND_SUBSCRIPTION = '/SECOND_SUBSCRIPTION';
  static const Profile='/profile';
  static const  mafcod='/list_of_mafcod';
  static const  Loast='/lost';
  static const  sign='/sign';
  static const start='/start';
  static const profile='/profile';
  static const find_job='/find_job';
  static const job_offer ='/job_offer';
  static const findjobprofile ='/FindJob';
  static const jobofferprofile ='/JobOfferProfile';
  static const changejobofferprofile ='/ChangeJobOffer';
  static const jobofferperson ='/JobOfferPerson';
  static const about ='/AboutP';
  static const deliver ='/Deliver';
  static const deliverprovider ='/DeliverProvider';
  static const deliverP ='/Deliver_P';
  static const DeliverProviderProfile ='/DeliverProviderProfile';
  static const changeDeliverP ='/changeDeliverP';
  static const DeliverPerson ='/DeliverPerson';
  static const changeDeliverProviderP ='/changeDeliverProviderP';
  static const DeliverPersonProfile ='/DeliverPersonProfile';
  static const  Changelost ='/Changelost';
  static const  ChangeMafcod ='/ChangeMafcod';
  static const  ChangeMafcodP ='/ChangeMafcodP';
  static const  NeedHelp ='/NeedHelp';
  static const  provideHelp ='/provideHelp';
  static const  NeedHelpPofile ='/NeedHelpPofile';
  static const  provideHelpProf ='/provideHelpProf';
  static const  changeNeed ='/changeNeed';
  static const  Person ='/Person';
  static const  liker ='/liker';
  static const  likerJob ='/likerJob';
  static const  provideJob ='/provideJob';
  static const  acceptJob ='/acceptJob';
  static const  likerOffer ='/likerOffer';
  static const  acceptOffer ='/acceptOffer';
  static const  likerDeliver ='/likerDeliver';
  static const  acceptDeliver ='/acceptDeliver';
  static const  likerProvider ='/likerProvider';
  static const  acceptProvider ='/acceptProvider';
  static const  acceptNeed ='/acceptNeed';
  static const  mafcodAbout ='/mafcodAbout';
  static const  jobAbout ='/jobAbout';
  static const  deliverAbout ='/deliverAbout';
  static const  helpAbout ='/helpAbout';
  static const  Posts ='/posts';
  static const  postUpdate ='/postUpdate';
  static const  enterEmail ='/enterEmail';
  static const  newPassword ='/newPassword';
  static const  commentPost ='/commentPost';
  static const  Contact ='/Contact';
  static const  LandingPage ='/LandingPage';
}
